In [1]:
#Installation of Numpy

In [2]:
!pip install numpy

In [8]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\user\anaconda3\lib\site-packages (1.18.3)


In [5]:
import numpy as np

In [6]:
array_one = np.array([1,2,3,4])

In [7]:
array_one

array([1, 2, 3, 4])

In [9]:
type(array_one)

numpy.ndarray

In [10]:
#assigning a list to array

In [11]:
numbers = [2,3,4,5,6,7,8]

In [12]:
array_two = np.array(numbers)

In [13]:
array_two

array([2, 3, 4, 5, 6, 7, 8])

In [14]:
#working with multi-dimentional array

In [15]:
array_of_zeros = np.zeros((3,4))

In [16]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
array_of_two = np.ones((3,4))

In [19]:
array_of_two

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# how to convert the default float data type to int type.

In [21]:
array_of_ones_int = np.ones((3,4), dtype=np.int16)

In [22]:
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)